package net.retrocarnage.editor.gameplayeditor.gui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.TransferHandler;
import net.retrocarnage.editor.gameplayeditor.impl.GamePlayEditorRepository;
import net.retrocarnage.editor.model.GamePlay;
import net.retrocarnage.editor.model.Mission;
import net.retrocarnage.editor.zoom.ZoomService;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.windows.TopComponent;

/**
 * Top component which displays the GamePlay of a Mission.
 */
@ConvertAsProperties(
        dtd = "-//net.retrocarnage.editor.gameplayeditor//GamePlayEditor//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GamePlayEditorTopComponent",
        iconBase = "net/retrocarnage/editor/gameplayeditor/gui/accessories-text-editor.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_GamePlayEditorAction=GamePlayEditor",
    "CTL_GamePlayEditorTopComponent=GamePlayEditor Window",
    "HINT_GamePlayEditorTopComponent=This is a GamePlayEditor window"
})
public final class GamePlayEditorTopComponent extends TopComponent implements PropertyChangeListener {

    private final GamePlayEditorController controller;
    private final TransferHandler transferHandler;

    public GamePlayEditorTopComponent() {
        this(null);
    }

    public GamePlayEditorTopComponent(final Mission mission) {
        controller = new GamePlayEditorController(mission);
        controller.addPropertyChangeListener(this);
        transferHandler = new DragAndDropTransferHandler(controller);
        ZoomService.getDefault().addPropertyChangeListener(this);

        associateLookup(new AbstractLookup(controller.getLookupContent()));

        initComponents();

        setName(Bundle.CTL_GamePlayEditorTopComponent());
        setToolTipText(Bundle.HINT_GamePlayEditorTopComponent());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code.
     *
     * The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPane = new javax.swing.JScrollPane();
        pnlDisplay = new GamePlayDisplay(scrPane);
        ((GamePlayDisplay) pnlDisplay).setGamePlay(getLookup().lookup(GamePlay.class));

        setLayout(new java.awt.BorderLayout());

        pnlDisplay.setTransferHandler(transferHandler);
        scrPane.setViewportView(pnlDisplay);

        add(scrPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JScrollPane scrPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        final Mission mission = controller.getMission();
        if (null != mission) {
            GamePlayEditorRepository.INSTANCE.register(mission.getId(), this);
            this.setDisplayName(mission.getName());
        }
    }

    @Override
    public void componentClosed() {
        final Mission mission = controller.getMission();
        if (null != mission) {
            GamePlayEditorRepository.INSTANCE.unregister(mission.getId(), this);
        }
        ZoomService.getDefault().removePropertyChangeListener(this);
        controller.removePropertyChangeListener(this);
        controller.close();
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        // String version = p.getProperty("version");
    }

    @Override
    public void propertyChange(final PropertyChangeEvent pce) {
        if (GamePlayEditorController.PROPERTY_GAMEPLAY.equals(pce.getPropertyName())) {
            ((GamePlayDisplay) pnlDisplay).setGamePlay(getLookup().lookup(GamePlay.class));
            System.out.println("GamePlayEditor has to be refreshed due to an external update");
        } else if (ZoomService.PROPERTY_ZOOM.equals(pce.getPropertyName())) {
            ((GamePlayDisplay) pnlDisplay).setGamePlay(getLookup().lookup(GamePlay.class));
            System.out.println("GamePlayEditor has to be refreshed due to change of zoom level");
        }
    }
}
