package net.retrocarnage.editor.zoom.gui;

import java.awt.event.MouseAdapter;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import net.retrocarnage.editor.zoom.ZoomService;
import net.retrocarnage.editor.zoom.impl.ZoomServiceImpl;

/**
 * Component that gets shown in the toolbar. Used to modify the zoom level of the game play editors.
 *
 * @author Thomas Werner
 */
public final class ZoomPanel extends javax.swing.JPanel implements PropertyChangeListener {

    /**
     * Creates new form ZoomPanel
     */
    public ZoomPanel() {
        ZoomService.getDefault().addPropertyChangeListener(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblZoomOut = new javax.swing.JLabel();
        sldZoom = new javax.swing.JSlider();
        javax.swing.JLabel lblZoomIn = new javax.swing.JLabel();
        lblZoomLevel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(lblZoomOut, org.openide.util.NbBundle.getMessage(ZoomPanel.class, "ZoomPanel.lblZoomOut.text_1")); // NOI18N
        lblZoomOut.addMouseListener(new ZoomOutMouseAdapter());

        sldZoom.setMajorTickSpacing(50);
        sldZoom.setMaximum(300);
        sldZoom.setMinimum(10);
        sldZoom.setMinorTickSpacing(10);
        sldZoom.setPaintTicks(true);
        sldZoom.setSnapToTicks(true);
        sldZoom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 3, 1));
        sldZoom.addChangeListener(l -> handleSliderChanged());

        org.openide.awt.Mnemonics.setLocalizedText(lblZoomIn, org.openide.util.NbBundle.getMessage(ZoomPanel.class, "ZoomPanel.lblZoomIn.text_1")); // NOI18N
        lblZoomIn.addMouseListener(new ZoomInMouseAdapter());

        org.openide.awt.Mnemonics.setLocalizedText(lblZoomLevel, org.openide.util.NbBundle.getMessage(ZoomPanel.class, "ZoomPanel.lblZoomLevel.text_1")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblZoomOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblZoomIn)
                .addGap(18, 18, 18)
                .addComponent(lblZoomLevel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblZoomIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sldZoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblZoomLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblZoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblZoomLevel;
    private javax.swing.JSlider sldZoom;
    // End of variables declaration//GEN-END:variables

    private void handleSliderChanged() {                                     
        if (!sldZoom.getValueIsAdjusting()) {
            final ZoomServiceImpl service = (ZoomServiceImpl) ZoomService.getDefault();
            service.setZoomLevel(sldZoom.getValue());
        }
    }       
        
    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if (ZoomService.PROPERTY_ZOOM.equals(pce.getPropertyName())) {
            sldZoom.setValue((int) pce.getNewValue());
            lblZoomLevel.setText(Integer.toString((int) pce.getNewValue()) + " %");
        }
    }
    
    private class ZoomOutMouseAdapter extends MouseAdapter {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            final ZoomServiceImpl service = (ZoomServiceImpl) ZoomService.getDefault();
            service.setZoomLevel(service.getZoomLevel() - 10);
        }
    }
    
    private class ZoomInMouseAdapter extends MouseAdapter {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            final ZoomServiceImpl service = (ZoomServiceImpl) ZoomService.getDefault();
            service.setZoomLevel(service.getZoomLevel() + 10);
        }
    }
    
}
