# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'        
    - name: Install NetBeans
      run: sudo snap install netbeans --classic
    - name: Build with Ant
      run: ant -Dnbplatform.default.netbeans.dest.dir=/snap/netbeans/89/netbeans -Dnbplatform.default.harness.dir=/snap/netbeans/89/netbeans/harness -noinput -buildfile build.xml       
