name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Download NetBeans
      run: wget https://dlcdn.apache.org/netbeans/netbeans-installers/23/apache-netbeans_23-1_all.deb
    - name: Install NetBeans  
      run: sudo dpkg -i apache-netbeans_23-1_all.deb
    - name: Remove NetBeans package
      run: rm apache-netbeans_23-1_all.deb
    - name: Build with Ant
      run: ant -Dnbplatform.default.netbeans.dest.dir=/usr/lib/apache-netbeans -Dnbplatform.default.harness.dir=/usr/lib/apache-netbeans/harness clean build
    - name: Run unit tests
      run: ant -Dnbplatform.default.netbeans.dest.dir=/usr/lib/apache-netbeans -Dnbplatform.default.harness.dir=/usr/lib/apache-netbeans/harness test
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
